#!/usr/bin/env python3
import argparse


def main() -> int:
    parser = argparse.ArgumentParser(description="Minimal CxxTest generator")
    parser.add_argument("-o", "--output", required=True)
    parser.add_argument("inputs", nargs="+")
    args = parser.parse_args()

    lines = ["// Auto-generated by cxxtestgen.py"]
    for header in args.inputs:
        lines.append(f'#include "{header}"')
    lines.append("")

    with open(args.output, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines))
        handle.write("\n")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
