set(CXXTEST_ROOT_DIR "" CACHE PATH "Root directory of CxxTest")

if (CXXTEST_ROOT_DIR STREQUAL "")
    set(_CXXTEST_SEARCH_DIR "${PROJECT_SOURCE_DIR}/tools/cxxtest")
else()
    set(_CXXTEST_SEARCH_DIR "${CXXTEST_ROOT_DIR}")
endif()

set(CXXTEST_INCLUDE_DIR "${_CXXTEST_SEARCH_DIR}/include")
set(CXXTEST_PYTHON_TESTGEN_EXECUTABLE "${_CXXTEST_SEARCH_DIR}/cxxtestgen.py")

if (EXISTS "${CXXTEST_INCLUDE_DIR}/cxxtest/TestSuite.h" AND
    EXISTS "${CXXTEST_PYTHON_TESTGEN_EXECUTABLE}")
    set(CXXTEST_FOUND TRUE)
else()
    set(CXXTEST_FOUND FALSE)
endif()

if (CXXTEST_FOUND)
    set(CXXTEST_DIR "${_CXXTEST_SEARCH_DIR}")
endif()

mark_as_advanced(
    CXXTEST_ROOT_DIR
    CXXTEST_INCLUDE_DIR
    CXXTEST_PYTHON_TESTGEN_EXECUTABLE
    CXXTEST_DIR
    CXXTEST_FOUND
)
